#ifndef MISTAKES_H
#define MISTAKES_H
#include <stdint.h>

typedef uint64_t TreeErr_t;

enum Err{
    NO_MISTAKE_T,
    NULL_NODE_PTR,
    INCORRECT_SIGN,
    INCORR_CONNECT_PARENT_CHILD,
    INCORR_LEFT_CONNECT,
    INCORR_RIGHT_CONNECT,
    LOOPED_NODE,
    INCORR_OUTPUT_FILE,
    CANT_OPEN_OUT_FILE,
    CANT_FIND_NODE,
    CANT_FIND_PATH,
    ALLOC_ERR,
    INCORR_VAR_TO_DIFF,
    INCORR_FILE,
    INCORR_OPERATOR,
    INCORR_TYPE,
    NO_ELEM_FOR_BINARY_OP,
};

#endif //MISTAKES_H