#ifndef MISTAKES_H
#define MISTAKES_H
#include <stdint.h>

typedef uint64_t TreeErr_t;

enum Err{
    NO_MISTAKE_T,
    NULL_NODE_PTR,
    INCORRECT_SIGN,
    INCORR_CONNECT_PARENT_CHILD,
    INCORR_LEFT_CONNECT,
    INCORR_RIGHT_CONNECT,
    INCORR_ANSWER,
    INCORR_OUTPUT_FILE,
    CANT_OPEN_OUT_FILE,
    CANT_FIND_NODE,
    CANT_FIND_PATH,
    INCORR_AKINATE_CONNECT,
    CANT_MAKE_DEF_COMP,
    INCORR_FILE,
    INCORR_OPERATOR,
};

#endif //MISTAKES_H